[package]
name = "iqdirectory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
iqstream.workspace = true
nostr-sdk = "0.45"
portmapper = { version = "0.19", default-features = false }
thiserror.workspace = true
tracing.workspace = true
tokio = { version = "1", features = ["rt", "time", "sync", "macros"] }

[dev-dependencies]
nostr-sdk = { version = "0.45", features = ["local-relay"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true
