[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "waveshark"
path = "src/main.rs"

[dependencies]
eframe = "0.35"
egui = "0.35"

common.workspace = true
dsp.workspace = true
audio.workspace = true
rtlsdr.workspace = true
hackrf.workspace = true
sources.workspace = true
nodes.workspace = true
decode.workspace = true
pipeline.workspace = true
crossbeam-channel.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
parking_lot.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png"] }
ureq = { version = "3.4.0", default-features = false, features = ["rustls"] }
