[package]
name = "iqstream"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
tracing.workspace = true
zstd = "0.13"
tokio = { version = "1", features = ["rt", "net", "io-util", "sync", "time", "macros"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
