[package]
name = "audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
cpal = "0.18"
thiserror.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.18", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
