/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LMS7Parameter {
    pub address: u16,
    pub msb: u8,
    pub lsb: u8,
    pub defaultValue: u16,
    pub name: *const ::std::os::raw::c_char,
    pub tooltip: *const ::std::os::raw::c_char,
}
pub type float_type = f64;
pub type lms_device_t = ::std::os::raw::c_void;
pub type lms_info_str_t = [::std::os::raw::c_char; 256usize];
pub type lms_name_t = [::std::os::raw::c_char; 16usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lms_range_t {
    pub min: float_type,
    pub max: float_type,
    pub step: float_type,
}
pub const lms_testsig_t_LMS_TESTSIG_NONE: lms_testsig_t = 0;
pub const lms_testsig_t_LMS_TESTSIG_NCODIV8: lms_testsig_t = 1;
pub const lms_testsig_t_LMS_TESTSIG_NCODIV4: lms_testsig_t = 2;
pub const lms_testsig_t_LMS_TESTSIG_NCODIV8F: lms_testsig_t = 3;
pub const lms_testsig_t_LMS_TESTSIG_NCODIV4F: lms_testsig_t = 4;
pub const lms_testsig_t_LMS_TESTSIG_DC: lms_testsig_t = 5;
pub type lms_testsig_t = ::std::os::raw::c_uint;
pub const lms_gfir_t_LMS_GFIR1: lms_gfir_t = 0;
pub const lms_gfir_t_LMS_GFIR2: lms_gfir_t = 1;
pub const lms_gfir_t_LMS_GFIR3: lms_gfir_t = 2;
pub type lms_gfir_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lms_stream_meta_t {
    pub timestamp: u64,
    pub waitForTimestamp: bool,
    pub flushPartialPacket: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lms_stream_t {
    pub handle: usize,
    pub isTx: bool,
    pub channel: u32,
    pub fifoSize: u32,
    pub throughputVsLatency: f32,
    pub dataFmt: lms_stream_t__bindgen_ty_1,
    pub linkFmt: lms_stream_t__bindgen_ty_2,
}
pub const lms_stream_t_LMS_FMT_F32: lms_stream_t__bindgen_ty_1 = 0;
pub const lms_stream_t_LMS_FMT_I16: lms_stream_t__bindgen_ty_1 = 1;
pub const lms_stream_t_LMS_FMT_I12: lms_stream_t__bindgen_ty_1 = 2;
pub type lms_stream_t__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const lms_stream_t_LMS_LINK_FMT_DEFAULT: lms_stream_t__bindgen_ty_2 = 0;
pub const lms_stream_t_LMS_LINK_FMT_I16: lms_stream_t__bindgen_ty_2 = 1;
pub const lms_stream_t_LMS_LINK_FMT_I12: lms_stream_t__bindgen_ty_2 = 2;
pub type lms_stream_t__bindgen_ty_2 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lms_stream_status_t {
    pub active: bool,
    pub fifoFilledCount: u32,
    pub fifoSize: u32,
    pub underrun: u32,
    pub overrun: u32,
    pub droppedPackets: u32,
    pub sampleRate: float_type,
    pub linkRate: float_type,
    pub timestamp: u64,
}
pub type lms_prog_callback_t = ::std::option::Option<
    unsafe extern "C" fn(
        bsent: ::std::os::raw::c_int,
        btotal: ::std::os::raw::c_int,
        progressMsg: *const ::std::os::raw::c_char,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct lms_dev_info_t {
    pub deviceName: [::std::os::raw::c_char; 32usize],
    pub expansionName: [::std::os::raw::c_char; 32usize],
    pub firmwareVersion: [::std::os::raw::c_char; 16usize],
    pub hardwareVersion: [::std::os::raw::c_char; 16usize],
    pub protocolVersion: [::std::os::raw::c_char; 16usize],
    pub boardSerialNumber: u64,
    pub gatewareVersion: [::std::os::raw::c_char; 16usize],
    pub gatewareTargetBoard: [::std::os::raw::c_char; 32usize],
}
pub type LMS_LogHandler = ::std::option::Option<
    unsafe extern "C" fn(lvl: ::std::os::raw::c_int, msg: *const ::std::os::raw::c_char),
>;
pub struct LimeSuiteLib {
    __library: ::libloading::Library,
    pub LMS_GetDeviceList: Result<
        unsafe extern "C" fn(dev_list: *mut lms_info_str_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Open: Result<
        unsafe extern "C" fn(
            device: *mut *mut lms_device_t,
            info: *const ::std::os::raw::c_char,
            args: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Close: Result<
        unsafe extern "C" fn(device: *mut lms_device_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Init: Result<
        unsafe extern "C" fn(device: *mut lms_device_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetNumChannels: Result<
        unsafe extern "C" fn(device: *mut lms_device_t, dir_tx: bool) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_EnableChannel: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            enabled: bool,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetSampleRate: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            rate: float_type,
            oversample: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetSampleRate: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            host_Hz: *mut float_type,
            rf_Hz: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetSampleRateRange: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            range: *mut lms_range_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetLOFrequency: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            frequency: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetLOFrequency: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            frequency: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetLOFrequencyRange: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            range: *mut lms_range_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetAntennaList: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            list: *mut lms_name_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetAntenna: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            index: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetAntenna: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetAntennaBW: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            index: usize,
            range: *mut lms_range_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetNormalizedGain: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            gain: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetGaindB: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            gain: ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetNormalizedGain: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            gain: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetGaindB: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            gain: *mut ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetLPFBW: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            bandwidth: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetLPFBW: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            bandwidth: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetLPFBWRange: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            range: *mut lms_range_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetLPF: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            enable: bool,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetGFIRLPF: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            enabled: bool,
            bandwidth: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Calibrate: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            bw: f64,
            flags: ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_LoadConfig: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            filename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SaveConfig: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            filename: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetTestSignal: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            sig: lms_testsig_t,
            dc_i: i16,
            dc_q: i16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetTestSignal: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            sig: *mut lms_testsig_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetChipTemperature: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            ind: usize,
            temp: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetSampleRateDir: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            rate: float_type,
            oversample: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetNCOFrequency: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            freq: *const float_type,
            pho: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetNCOFrequency: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            freq: *mut float_type,
            pho: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetNCOPhase: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            phases: *const float_type,
            fcw: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetNCOPhase: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            phases: *mut float_type,
            fcw: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetNCOIndex: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            index: ::std::os::raw::c_int,
            downconv: bool,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetNCOIndex: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetGFIRCoeff: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            filt: lms_gfir_t,
            coef: *const float_type,
            count: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetGFIRCoeff: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            filt: lms_gfir_t,
            coef: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetGFIR: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            dir_tx: bool,
            chan: usize,
            filt: lms_gfir_t,
            enabled: bool,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_EnableCache: Result<
        unsafe extern "C" fn(dev: *mut lms_device_t, enable: bool) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Reset: Result<
        unsafe extern "C" fn(device: *mut lms_device_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_ReadLMSReg: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            address: u32,
            val: *mut u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_WriteLMSReg: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            address: u32,
            val: u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_ReadParam: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            param: LMS7Parameter,
            val: *mut u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_WriteParam: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            param: LMS7Parameter,
            val: u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_ReadFPGAReg: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            address: u32,
            val: *mut u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_WriteFPGAReg: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            address: u32,
            val: u16,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_ReadCustomBoardParam: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            id: u8,
            val: *mut float_type,
            units: *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_WriteCustomBoardParam: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            id: u8,
            val: float_type,
            units: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetClockFreq: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            clk_id: usize,
            freq: *mut float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetClockFreq: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            clk_id: usize,
            freq: float_type,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_VCTCXOWrite: Result<
        unsafe extern "C" fn(dev: *mut lms_device_t, val: u16) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_VCTCXORead: Result<
        unsafe extern "C" fn(dev: *mut lms_device_t, val: *mut u16) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Synchronize: Result<
        unsafe extern "C" fn(dev: *mut lms_device_t, toChip: bool) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GPIORead: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            buffer: *mut u8,
            len: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GPIOWrite: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            buffer: *const u8,
            len: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GPIODirRead: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            buffer: *mut u8,
            len: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GPIODirWrite: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            buffer: *const u8,
            len: usize,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SetupStream: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            stream: *mut lms_stream_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_DestroyStream: Result<
        unsafe extern "C" fn(
            dev: *mut lms_device_t,
            stream: *mut lms_stream_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_StartStream: Result<
        unsafe extern "C" fn(stream: *mut lms_stream_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_StopStream: Result<
        unsafe extern "C" fn(stream: *mut lms_stream_t) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_RecvStream: Result<
        unsafe extern "C" fn(
            stream: *mut lms_stream_t,
            samples: *mut ::std::os::raw::c_void,
            sample_count: usize,
            meta: *mut lms_stream_meta_t,
            timeout_ms: ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetStreamStatus: Result<
        unsafe extern "C" fn(
            stream: *mut lms_stream_t,
            status: *mut lms_stream_status_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_SendStream: Result<
        unsafe extern "C" fn(
            stream: *mut lms_stream_t,
            samples: *const ::std::os::raw::c_void,
            sample_count: usize,
            meta: *const lms_stream_meta_t,
            timeout_ms: ::std::os::raw::c_uint,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_UploadWFM: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            samples: *mut *const ::std::os::raw::c_void,
            chCount: u8,
            sample_count: usize,
            format: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_EnableTxWFM: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            chan: ::std::os::raw::c_uint,
            active: bool,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetProgramModes: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            list: *mut lms_name_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_Program: Result<
        unsafe extern "C" fn(
            device: *mut lms_device_t,
            data: *const ::std::os::raw::c_char,
            size: usize,
            mode: *const ::std::os::raw::c_char,
            callback: lms_prog_callback_t,
        ) -> ::std::os::raw::c_int,
        ::libloading::Error,
    >,
    pub LMS_GetDeviceInfo: Result<
        unsafe extern "C" fn(device: *mut lms_device_t) -> *const lms_dev_info_t,
        ::libloading::Error,
    >,
    pub LMS_GetLibraryVersion:
        Result<unsafe extern "C" fn() -> *const ::std::os::raw::c_char, ::libloading::Error>,
    pub LMS_GetLastErrorMessage:
        Result<unsafe extern "C" fn() -> *const ::std::os::raw::c_char, ::libloading::Error>,
    pub LMS_RegisterLogHandler:
        Result<unsafe extern "C" fn(handler: LMS_LogHandler), ::libloading::Error>,
}
impl LimeSuiteLib {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let LMS_GetDeviceList = __library.get(b"LMS_GetDeviceList\0").map(|sym| *sym);
        let LMS_Open = __library.get(b"LMS_Open\0").map(|sym| *sym);
        let LMS_Close = __library.get(b"LMS_Close\0").map(|sym| *sym);
        let LMS_Init = __library.get(b"LMS_Init\0").map(|sym| *sym);
        let LMS_GetNumChannels = __library.get(b"LMS_GetNumChannels\0").map(|sym| *sym);
        let LMS_EnableChannel = __library.get(b"LMS_EnableChannel\0").map(|sym| *sym);
        let LMS_SetSampleRate = __library.get(b"LMS_SetSampleRate\0").map(|sym| *sym);
        let LMS_GetSampleRate = __library.get(b"LMS_GetSampleRate\0").map(|sym| *sym);
        let LMS_GetSampleRateRange = __library.get(b"LMS_GetSampleRateRange\0").map(|sym| *sym);
        let LMS_SetLOFrequency = __library.get(b"LMS_SetLOFrequency\0").map(|sym| *sym);
        let LMS_GetLOFrequency = __library.get(b"LMS_GetLOFrequency\0").map(|sym| *sym);
        let LMS_GetLOFrequencyRange = __library.get(b"LMS_GetLOFrequencyRange\0").map(|sym| *sym);
        let LMS_GetAntennaList = __library.get(b"LMS_GetAntennaList\0").map(|sym| *sym);
        let LMS_SetAntenna = __library.get(b"LMS_SetAntenna\0").map(|sym| *sym);
        let LMS_GetAntenna = __library.get(b"LMS_GetAntenna\0").map(|sym| *sym);
        let LMS_GetAntennaBW = __library.get(b"LMS_GetAntennaBW\0").map(|sym| *sym);
        let LMS_SetNormalizedGain = __library.get(b"LMS_SetNormalizedGain\0").map(|sym| *sym);
        let LMS_SetGaindB = __library.get(b"LMS_SetGaindB\0").map(|sym| *sym);
        let LMS_GetNormalizedGain = __library.get(b"LMS_GetNormalizedGain\0").map(|sym| *sym);
        let LMS_GetGaindB = __library.get(b"LMS_GetGaindB\0").map(|sym| *sym);
        let LMS_SetLPFBW = __library.get(b"LMS_SetLPFBW\0").map(|sym| *sym);
        let LMS_GetLPFBW = __library.get(b"LMS_GetLPFBW\0").map(|sym| *sym);
        let LMS_GetLPFBWRange = __library.get(b"LMS_GetLPFBWRange\0").map(|sym| *sym);
        let LMS_SetLPF = __library.get(b"LMS_SetLPF\0").map(|sym| *sym);
        let LMS_SetGFIRLPF = __library.get(b"LMS_SetGFIRLPF\0").map(|sym| *sym);
        let LMS_Calibrate = __library.get(b"LMS_Calibrate\0").map(|sym| *sym);
        let LMS_LoadConfig = __library.get(b"LMS_LoadConfig\0").map(|sym| *sym);
        let LMS_SaveConfig = __library.get(b"LMS_SaveConfig\0").map(|sym| *sym);
        let LMS_SetTestSignal = __library.get(b"LMS_SetTestSignal\0").map(|sym| *sym);
        let LMS_GetTestSignal = __library.get(b"LMS_GetTestSignal\0").map(|sym| *sym);
        let LMS_GetChipTemperature = __library.get(b"LMS_GetChipTemperature\0").map(|sym| *sym);
        let LMS_SetSampleRateDir = __library.get(b"LMS_SetSampleRateDir\0").map(|sym| *sym);
        let LMS_SetNCOFrequency = __library.get(b"LMS_SetNCOFrequency\0").map(|sym| *sym);
        let LMS_GetNCOFrequency = __library.get(b"LMS_GetNCOFrequency\0").map(|sym| *sym);
        let LMS_SetNCOPhase = __library.get(b"LMS_SetNCOPhase\0").map(|sym| *sym);
        let LMS_GetNCOPhase = __library.get(b"LMS_GetNCOPhase\0").map(|sym| *sym);
        let LMS_SetNCOIndex = __library.get(b"LMS_SetNCOIndex\0").map(|sym| *sym);
        let LMS_GetNCOIndex = __library.get(b"LMS_GetNCOIndex\0").map(|sym| *sym);
        let LMS_SetGFIRCoeff = __library.get(b"LMS_SetGFIRCoeff\0").map(|sym| *sym);
        let LMS_GetGFIRCoeff = __library.get(b"LMS_GetGFIRCoeff\0").map(|sym| *sym);
        let LMS_SetGFIR = __library.get(b"LMS_SetGFIR\0").map(|sym| *sym);
        let LMS_EnableCache = __library.get(b"LMS_EnableCache\0").map(|sym| *sym);
        let LMS_Reset = __library.get(b"LMS_Reset\0").map(|sym| *sym);
        let LMS_ReadLMSReg = __library.get(b"LMS_ReadLMSReg\0").map(|sym| *sym);
        let LMS_WriteLMSReg = __library.get(b"LMS_WriteLMSReg\0").map(|sym| *sym);
        let LMS_ReadParam = __library.get(b"LMS_ReadParam\0").map(|sym| *sym);
        let LMS_WriteParam = __library.get(b"LMS_WriteParam\0").map(|sym| *sym);
        let LMS_ReadFPGAReg = __library.get(b"LMS_ReadFPGAReg\0").map(|sym| *sym);
        let LMS_WriteFPGAReg = __library.get(b"LMS_WriteFPGAReg\0").map(|sym| *sym);
        let LMS_ReadCustomBoardParam = __library.get(b"LMS_ReadCustomBoardParam\0").map(|sym| *sym);
        let LMS_WriteCustomBoardParam =
            __library.get(b"LMS_WriteCustomBoardParam\0").map(|sym| *sym);
        let LMS_GetClockFreq = __library.get(b"LMS_GetClockFreq\0").map(|sym| *sym);
        let LMS_SetClockFreq = __library.get(b"LMS_SetClockFreq\0").map(|sym| *sym);
        let LMS_VCTCXOWrite = __library.get(b"LMS_VCTCXOWrite\0").map(|sym| *sym);
        let LMS_VCTCXORead = __library.get(b"LMS_VCTCXORead\0").map(|sym| *sym);
        let LMS_Synchronize = __library.get(b"LMS_Synchronize\0").map(|sym| *sym);
        let LMS_GPIORead = __library.get(b"LMS_GPIORead\0").map(|sym| *sym);
        let LMS_GPIOWrite = __library.get(b"LMS_GPIOWrite\0").map(|sym| *sym);
        let LMS_GPIODirRead = __library.get(b"LMS_GPIODirRead\0").map(|sym| *sym);
        let LMS_GPIODirWrite = __library.get(b"LMS_GPIODirWrite\0").map(|sym| *sym);
        let LMS_SetupStream = __library.get(b"LMS_SetupStream\0").map(|sym| *sym);
        let LMS_DestroyStream = __library.get(b"LMS_DestroyStream\0").map(|sym| *sym);
        let LMS_StartStream = __library.get(b"LMS_StartStream\0").map(|sym| *sym);
        let LMS_StopStream = __library.get(b"LMS_StopStream\0").map(|sym| *sym);
        let LMS_RecvStream = __library.get(b"LMS_RecvStream\0").map(|sym| *sym);
        let LMS_GetStreamStatus = __library.get(b"LMS_GetStreamStatus\0").map(|sym| *sym);
        let LMS_SendStream = __library.get(b"LMS_SendStream\0").map(|sym| *sym);
        let LMS_UploadWFM = __library.get(b"LMS_UploadWFM\0").map(|sym| *sym);
        let LMS_EnableTxWFM = __library.get(b"LMS_EnableTxWFM\0").map(|sym| *sym);
        let LMS_GetProgramModes = __library.get(b"LMS_GetProgramModes\0").map(|sym| *sym);
        let LMS_Program = __library.get(b"LMS_Program\0").map(|sym| *sym);
        let LMS_GetDeviceInfo = __library.get(b"LMS_GetDeviceInfo\0").map(|sym| *sym);
        let LMS_GetLibraryVersion = __library.get(b"LMS_GetLibraryVersion\0").map(|sym| *sym);
        let LMS_GetLastErrorMessage = __library.get(b"LMS_GetLastErrorMessage\0").map(|sym| *sym);
        let LMS_RegisterLogHandler = __library.get(b"LMS_RegisterLogHandler\0").map(|sym| *sym);
        Ok(LimeSuiteLib {
            __library,
            LMS_GetDeviceList,
            LMS_Open,
            LMS_Close,
            LMS_Init,
            LMS_GetNumChannels,
            LMS_EnableChannel,
            LMS_SetSampleRate,
            LMS_GetSampleRate,
            LMS_GetSampleRateRange,
            LMS_SetLOFrequency,
            LMS_GetLOFrequency,
            LMS_GetLOFrequencyRange,
            LMS_GetAntennaList,
            LMS_SetAntenna,
            LMS_GetAntenna,
            LMS_GetAntennaBW,
            LMS_SetNormalizedGain,
            LMS_SetGaindB,
            LMS_GetNormalizedGain,
            LMS_GetGaindB,
            LMS_SetLPFBW,
            LMS_GetLPFBW,
            LMS_GetLPFBWRange,
            LMS_SetLPF,
            LMS_SetGFIRLPF,
            LMS_Calibrate,
            LMS_LoadConfig,
            LMS_SaveConfig,
            LMS_SetTestSignal,
            LMS_GetTestSignal,
            LMS_GetChipTemperature,
            LMS_SetSampleRateDir,
            LMS_SetNCOFrequency,
            LMS_GetNCOFrequency,
            LMS_SetNCOPhase,
            LMS_GetNCOPhase,
            LMS_SetNCOIndex,
            LMS_GetNCOIndex,
            LMS_SetGFIRCoeff,
            LMS_GetGFIRCoeff,
            LMS_SetGFIR,
            LMS_EnableCache,
            LMS_Reset,
            LMS_ReadLMSReg,
            LMS_WriteLMSReg,
            LMS_ReadParam,
            LMS_WriteParam,
            LMS_ReadFPGAReg,
            LMS_WriteFPGAReg,
            LMS_ReadCustomBoardParam,
            LMS_WriteCustomBoardParam,
            LMS_GetClockFreq,
            LMS_SetClockFreq,
            LMS_VCTCXOWrite,
            LMS_VCTCXORead,
            LMS_Synchronize,
            LMS_GPIORead,
            LMS_GPIOWrite,
            LMS_GPIODirRead,
            LMS_GPIODirWrite,
            LMS_SetupStream,
            LMS_DestroyStream,
            LMS_StartStream,
            LMS_StopStream,
            LMS_RecvStream,
            LMS_GetStreamStatus,
            LMS_SendStream,
            LMS_UploadWFM,
            LMS_EnableTxWFM,
            LMS_GetProgramModes,
            LMS_Program,
            LMS_GetDeviceInfo,
            LMS_GetLibraryVersion,
            LMS_GetLastErrorMessage,
            LMS_RegisterLogHandler,
        })
    }
    pub unsafe fn LMS_GetDeviceList(&self, dev_list: *mut lms_info_str_t) -> ::std::os::raw::c_int {
        (self.LMS_GetDeviceList.as_ref().expect("Expected function, got error."))(dev_list)
    }
    pub unsafe fn LMS_Open(
        &self,
        device: *mut *mut lms_device_t,
        info: *const ::std::os::raw::c_char,
        args: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int {
        (self.LMS_Open.as_ref().expect("Expected function, got error."))(device, info, args)
    }
    pub unsafe fn LMS_Close(&self, device: *mut lms_device_t) -> ::std::os::raw::c_int {
        (self.LMS_Close.as_ref().expect("Expected function, got error."))(device)
    }
    pub unsafe fn LMS_Init(&self, device: *mut lms_device_t) -> ::std::os::raw::c_int {
        (self.LMS_Init.as_ref().expect("Expected function, got error."))(device)
    }
    pub unsafe fn LMS_GetNumChannels(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetNumChannels.as_ref().expect("Expected function, got error."))(device, dir_tx)
    }
    pub unsafe fn LMS_EnableChannel(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        enabled: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_EnableChannel.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, enabled,
        )
    }
    pub unsafe fn LMS_SetSampleRate(
        &self,
        device: *mut lms_device_t,
        rate: float_type,
        oversample: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetSampleRate.as_ref().expect("Expected function, got error."))(
            device, rate, oversample,
        )
    }
    pub unsafe fn LMS_GetSampleRate(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        host_Hz: *mut float_type,
        rf_Hz: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetSampleRate.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, host_Hz, rf_Hz,
        )
    }
    pub unsafe fn LMS_GetSampleRateRange(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        range: *mut lms_range_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetSampleRateRange.as_ref().expect("Expected function, got error."))(
            device, dir_tx, range,
        )
    }
    pub unsafe fn LMS_SetLOFrequency(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        frequency: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetLOFrequency.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, frequency,
        )
    }
    pub unsafe fn LMS_GetLOFrequency(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        frequency: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetLOFrequency.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, frequency,
        )
    }
    pub unsafe fn LMS_GetLOFrequencyRange(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        range: *mut lms_range_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetLOFrequencyRange.as_ref().expect("Expected function, got error."))(
            device, dir_tx, range,
        )
    }
    pub unsafe fn LMS_GetAntennaList(
        &self,
        dev: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        list: *mut lms_name_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetAntennaList.as_ref().expect("Expected function, got error."))(
            dev, dir_tx, chan, list,
        )
    }
    pub unsafe fn LMS_SetAntenna(
        &self,
        dev: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        index: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetAntenna.as_ref().expect("Expected function, got error."))(
            dev, dir_tx, chan, index,
        )
    }
    pub unsafe fn LMS_GetAntenna(
        &self,
        dev: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetAntenna.as_ref().expect("Expected function, got error."))(dev, dir_tx, chan)
    }
    pub unsafe fn LMS_GetAntennaBW(
        &self,
        dev: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        index: usize,
        range: *mut lms_range_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetAntennaBW.as_ref().expect("Expected function, got error."))(
            dev, dir_tx, chan, index, range,
        )
    }
    pub unsafe fn LMS_SetNormalizedGain(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        gain: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetNormalizedGain.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, gain,
        )
    }
    pub unsafe fn LMS_SetGaindB(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        gain: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetGaindB.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, gain,
        )
    }
    pub unsafe fn LMS_GetNormalizedGain(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        gain: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetNormalizedGain.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, gain,
        )
    }
    pub unsafe fn LMS_GetGaindB(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        gain: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetGaindB.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, gain,
        )
    }
    pub unsafe fn LMS_SetLPFBW(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        bandwidth: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetLPFBW.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, bandwidth,
        )
    }
    pub unsafe fn LMS_GetLPFBW(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        bandwidth: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetLPFBW.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, bandwidth,
        )
    }
    pub unsafe fn LMS_GetLPFBWRange(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        range: *mut lms_range_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetLPFBWRange.as_ref().expect("Expected function, got error."))(
            device, dir_tx, range,
        )
    }
    pub unsafe fn LMS_SetLPF(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        enable: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetLPF.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, enable,
        )
    }
    pub unsafe fn LMS_SetGFIRLPF(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        enabled: bool,
        bandwidth: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetGFIRLPF.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, enabled, bandwidth,
        )
    }
    pub unsafe fn LMS_Calibrate(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        bw: f64,
        flags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int {
        (self.LMS_Calibrate.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, bw, flags,
        )
    }
    pub unsafe fn LMS_LoadConfig(
        &self,
        device: *mut lms_device_t,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.LMS_LoadConfig.as_ref().expect("Expected function, got error."))(device, filename)
    }
    pub unsafe fn LMS_SaveConfig(
        &self,
        device: *mut lms_device_t,
        filename: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SaveConfig.as_ref().expect("Expected function, got error."))(device, filename)
    }
    pub unsafe fn LMS_SetTestSignal(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        sig: lms_testsig_t,
        dc_i: i16,
        dc_q: i16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetTestSignal.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, sig, dc_i, dc_q,
        )
    }
    pub unsafe fn LMS_GetTestSignal(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        sig: *mut lms_testsig_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetTestSignal.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, sig,
        )
    }
    pub unsafe fn LMS_GetChipTemperature(
        &self,
        dev: *mut lms_device_t,
        ind: usize,
        temp: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetChipTemperature.as_ref().expect("Expected function, got error."))(
            dev, ind, temp,
        )
    }
    pub unsafe fn LMS_SetSampleRateDir(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        rate: float_type,
        oversample: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetSampleRateDir.as_ref().expect("Expected function, got error."))(
            device, dir_tx, rate, oversample,
        )
    }
    pub unsafe fn LMS_SetNCOFrequency(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        freq: *const float_type,
        pho: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetNCOFrequency.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, freq, pho,
        )
    }
    pub unsafe fn LMS_GetNCOFrequency(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        freq: *mut float_type,
        pho: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetNCOFrequency.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, freq, pho,
        )
    }
    pub unsafe fn LMS_SetNCOPhase(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        phases: *const float_type,
        fcw: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetNCOPhase.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, phases, fcw,
        )
    }
    pub unsafe fn LMS_GetNCOPhase(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        phases: *mut float_type,
        fcw: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetNCOPhase.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, phases, fcw,
        )
    }
    pub unsafe fn LMS_SetNCOIndex(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        index: ::std::os::raw::c_int,
        downconv: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetNCOIndex.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, index, downconv,
        )
    }
    pub unsafe fn LMS_GetNCOIndex(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetNCOIndex.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan,
        )
    }
    pub unsafe fn LMS_SetGFIRCoeff(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        filt: lms_gfir_t,
        coef: *const float_type,
        count: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetGFIRCoeff.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, filt, coef, count,
        )
    }
    pub unsafe fn LMS_GetGFIRCoeff(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        filt: lms_gfir_t,
        coef: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetGFIRCoeff.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, filt, coef,
        )
    }
    pub unsafe fn LMS_SetGFIR(
        &self,
        device: *mut lms_device_t,
        dir_tx: bool,
        chan: usize,
        filt: lms_gfir_t,
        enabled: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetGFIR.as_ref().expect("Expected function, got error."))(
            device, dir_tx, chan, filt, enabled,
        )
    }
    pub unsafe fn LMS_EnableCache(
        &self,
        dev: *mut lms_device_t,
        enable: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_EnableCache.as_ref().expect("Expected function, got error."))(dev, enable)
    }
    pub unsafe fn LMS_Reset(&self, device: *mut lms_device_t) -> ::std::os::raw::c_int {
        (self.LMS_Reset.as_ref().expect("Expected function, got error."))(device)
    }
    pub unsafe fn LMS_ReadLMSReg(
        &self,
        device: *mut lms_device_t,
        address: u32,
        val: *mut u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_ReadLMSReg.as_ref().expect("Expected function, got error."))(device, address, val)
    }
    pub unsafe fn LMS_WriteLMSReg(
        &self,
        device: *mut lms_device_t,
        address: u32,
        val: u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_WriteLMSReg.as_ref().expect("Expected function, got error."))(
            device, address, val,
        )
    }
    pub unsafe fn LMS_ReadParam(
        &self,
        device: *mut lms_device_t,
        param: LMS7Parameter,
        val: *mut u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_ReadParam.as_ref().expect("Expected function, got error."))(device, param, val)
    }
    pub unsafe fn LMS_WriteParam(
        &self,
        device: *mut lms_device_t,
        param: LMS7Parameter,
        val: u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_WriteParam.as_ref().expect("Expected function, got error."))(device, param, val)
    }
    pub unsafe fn LMS_ReadFPGAReg(
        &self,
        device: *mut lms_device_t,
        address: u32,
        val: *mut u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_ReadFPGAReg.as_ref().expect("Expected function, got error."))(
            device, address, val,
        )
    }
    pub unsafe fn LMS_WriteFPGAReg(
        &self,
        device: *mut lms_device_t,
        address: u32,
        val: u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_WriteFPGAReg.as_ref().expect("Expected function, got error."))(
            device, address, val,
        )
    }
    pub unsafe fn LMS_ReadCustomBoardParam(
        &self,
        device: *mut lms_device_t,
        id: u8,
        val: *mut float_type,
        units: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.LMS_ReadCustomBoardParam.as_ref().expect("Expected function, got error."))(
            device, id, val, units,
        )
    }
    pub unsafe fn LMS_WriteCustomBoardParam(
        &self,
        device: *mut lms_device_t,
        id: u8,
        val: float_type,
        units: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        (self.LMS_WriteCustomBoardParam.as_ref().expect("Expected function, got error."))(
            device, id, val, units,
        )
    }
    pub unsafe fn LMS_GetClockFreq(
        &self,
        dev: *mut lms_device_t,
        clk_id: usize,
        freq: *mut float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetClockFreq.as_ref().expect("Expected function, got error."))(dev, clk_id, freq)
    }
    pub unsafe fn LMS_SetClockFreq(
        &self,
        dev: *mut lms_device_t,
        clk_id: usize,
        freq: float_type,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetClockFreq.as_ref().expect("Expected function, got error."))(dev, clk_id, freq)
    }
    pub unsafe fn LMS_VCTCXOWrite(
        &self,
        dev: *mut lms_device_t,
        val: u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_VCTCXOWrite.as_ref().expect("Expected function, got error."))(dev, val)
    }
    pub unsafe fn LMS_VCTCXORead(
        &self,
        dev: *mut lms_device_t,
        val: *mut u16,
    ) -> ::std::os::raw::c_int {
        (self.LMS_VCTCXORead.as_ref().expect("Expected function, got error."))(dev, val)
    }
    pub unsafe fn LMS_Synchronize(
        &self,
        dev: *mut lms_device_t,
        toChip: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_Synchronize.as_ref().expect("Expected function, got error."))(dev, toChip)
    }
    pub unsafe fn LMS_GPIORead(
        &self,
        dev: *mut lms_device_t,
        buffer: *mut u8,
        len: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GPIORead.as_ref().expect("Expected function, got error."))(dev, buffer, len)
    }
    pub unsafe fn LMS_GPIOWrite(
        &self,
        dev: *mut lms_device_t,
        buffer: *const u8,
        len: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GPIOWrite.as_ref().expect("Expected function, got error."))(dev, buffer, len)
    }
    pub unsafe fn LMS_GPIODirRead(
        &self,
        dev: *mut lms_device_t,
        buffer: *mut u8,
        len: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GPIODirRead.as_ref().expect("Expected function, got error."))(dev, buffer, len)
    }
    pub unsafe fn LMS_GPIODirWrite(
        &self,
        dev: *mut lms_device_t,
        buffer: *const u8,
        len: usize,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GPIODirWrite.as_ref().expect("Expected function, got error."))(dev, buffer, len)
    }
    pub unsafe fn LMS_SetupStream(
        &self,
        device: *mut lms_device_t,
        stream: *mut lms_stream_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SetupStream.as_ref().expect("Expected function, got error."))(device, stream)
    }
    pub unsafe fn LMS_DestroyStream(
        &self,
        dev: *mut lms_device_t,
        stream: *mut lms_stream_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_DestroyStream.as_ref().expect("Expected function, got error."))(dev, stream)
    }
    pub unsafe fn LMS_StartStream(&self, stream: *mut lms_stream_t) -> ::std::os::raw::c_int {
        (self.LMS_StartStream.as_ref().expect("Expected function, got error."))(stream)
    }
    pub unsafe fn LMS_StopStream(&self, stream: *mut lms_stream_t) -> ::std::os::raw::c_int {
        (self.LMS_StopStream.as_ref().expect("Expected function, got error."))(stream)
    }
    pub unsafe fn LMS_RecvStream(
        &self,
        stream: *mut lms_stream_t,
        samples: *mut ::std::os::raw::c_void,
        sample_count: usize,
        meta: *mut lms_stream_meta_t,
        timeout_ms: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int {
        (self.LMS_RecvStream.as_ref().expect("Expected function, got error."))(
            stream,
            samples,
            sample_count,
            meta,
            timeout_ms,
        )
    }
    pub unsafe fn LMS_GetStreamStatus(
        &self,
        stream: *mut lms_stream_t,
        status: *mut lms_stream_status_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetStreamStatus.as_ref().expect("Expected function, got error."))(stream, status)
    }
    pub unsafe fn LMS_SendStream(
        &self,
        stream: *mut lms_stream_t,
        samples: *const ::std::os::raw::c_void,
        sample_count: usize,
        meta: *const lms_stream_meta_t,
        timeout_ms: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int {
        (self.LMS_SendStream.as_ref().expect("Expected function, got error."))(
            stream,
            samples,
            sample_count,
            meta,
            timeout_ms,
        )
    }
    pub unsafe fn LMS_UploadWFM(
        &self,
        device: *mut lms_device_t,
        samples: *mut *const ::std::os::raw::c_void,
        chCount: u8,
        sample_count: usize,
        format: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        (self.LMS_UploadWFM.as_ref().expect("Expected function, got error."))(
            device,
            samples,
            chCount,
            sample_count,
            format,
        )
    }
    pub unsafe fn LMS_EnableTxWFM(
        &self,
        device: *mut lms_device_t,
        chan: ::std::os::raw::c_uint,
        active: bool,
    ) -> ::std::os::raw::c_int {
        (self.LMS_EnableTxWFM.as_ref().expect("Expected function, got error."))(
            device, chan, active,
        )
    }
    pub unsafe fn LMS_GetProgramModes(
        &self,
        device: *mut lms_device_t,
        list: *mut lms_name_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_GetProgramModes.as_ref().expect("Expected function, got error."))(device, list)
    }
    pub unsafe fn LMS_Program(
        &self,
        device: *mut lms_device_t,
        data: *const ::std::os::raw::c_char,
        size: usize,
        mode: *const ::std::os::raw::c_char,
        callback: lms_prog_callback_t,
    ) -> ::std::os::raw::c_int {
        (self.LMS_Program.as_ref().expect("Expected function, got error."))(
            device, data, size, mode, callback,
        )
    }
    pub unsafe fn LMS_GetDeviceInfo(&self, device: *mut lms_device_t) -> *const lms_dev_info_t {
        (self.LMS_GetDeviceInfo.as_ref().expect("Expected function, got error."))(device)
    }
    pub unsafe fn LMS_GetLibraryVersion(&self) -> *const ::std::os::raw::c_char {
        (self.LMS_GetLibraryVersion.as_ref().expect("Expected function, got error."))()
    }
    pub unsafe fn LMS_GetLastErrorMessage(&self) -> *const ::std::os::raw::c_char {
        (self.LMS_GetLastErrorMessage.as_ref().expect("Expected function, got error."))()
    }
    pub unsafe fn LMS_RegisterLogHandler(&self, handler: LMS_LogHandler) {
        (self.LMS_RegisterLogHandler.as_ref().expect("Expected function, got error."))(handler)
    }
}
