//! Raw FFI bindings to LimeSuite's LMS API, generated by bindgen at build time.
//!
//! Nothing here is safe. Use the `limesdr` crate instead.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// `LMS_SUCCESS`. The header defines it as a `static const int`, which is not
/// an exported symbol, so it cannot come from bindgen.
pub const LMS_SUCCESS: i32 = 0;

/// Direction selectors. `dir_tx` is a bool in the C API.
pub const LMS_CH_RX: bool = false;
pub const LMS_CH_TX: bool = true;

/// `lms_stream_t::dataFmt` values, which bindgen anonymises.
pub const LMS_FMT_F32: u32 = 0;
pub const LMS_FMT_I16: u32 = 1;
pub const LMS_FMT_I12: u32 = 2;

/// `lms_stream_t::linkFmt` values.
pub const LMS_LINK_FMT_DEFAULT: u32 = 0;
pub const LMS_LINK_FMT_I16: u32 = 1;
pub const LMS_LINK_FMT_I12: u32 = 2;
