//! Raw FFI bindings to LimeSuite's LMS API, generated by bindgen at build time.
//!
//! The library is opened by name on first use rather than linked, because its
//! soname carries its version (`libLimeSuite.so.20.10-1`) and a release binary
//! would otherwise refuse to start on any machine whose LimeSuite is a
//! different release, or which has none. Without it every call here fails and
//! the device list is empty.
//!
//! Nothing here is safe. Use the `limesdr` crate instead.

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, unsafe_op_in_unsafe_fn, clippy::all)]

use std::ffi::OsString;
use std::sync::OnceLock;

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// `LMS_SUCCESS`. The header defines it as a `static const int`, which is not
/// an exported symbol, so it cannot come from bindgen.
pub const LMS_SUCCESS: i32 = 0;

/// What every shim returns when LimeSuite is not on the machine
const LMS_ERROR: i32 = -1;

/// Direction selectors. `dir_tx` is a bool in the C API.
pub const LMS_CH_RX: bool = false;
pub const LMS_CH_TX: bool = true;

/// `lms_stream_t::dataFmt` values, which bindgen anonymises.
pub const LMS_FMT_F32: u32 = 0;
pub const LMS_FMT_I16: u32 = 1;
pub const LMS_FMT_I12: u32 = 2;

/// `lms_stream_t::linkFmt` values.
pub const LMS_LINK_FMT_DEFAULT: u32 = 0;
pub const LMS_LINK_FMT_I16: u32 = 1;
pub const LMS_LINK_FMT_I12: u32 = 2;

static LIB: OnceLock<Option<LimeSuiteLib>> = OnceLock::new();

/// Whether LimeSuite was found, and so whether a LimeSDR can be opened at all
pub fn available() -> bool {
    lib().is_some()
}

fn lib() -> Option<&'static LimeSuiteLib> {
    LIB.get_or_init(|| {
        for name in candidates() {
            // SAFETY: an initialiser in the library runs on load, as it does
            // for anything linked the ordinary way.
            if let Ok(l) = unsafe { LimeSuiteLib::new(&name) } {
                return Some(l);
            }
        }
        None
    })
    .as_ref()
}

/// Every filename worth trying, most specific first.
fn candidates() -> Vec<OsString> {
    let mut out: Vec<OsString> = Vec::new();

    // A bundle carries its own copy beside the binary, where dlopen will not
    // look by itself, so that one is given as a path.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            for rel in ["../Resources/libLimeSuite.dylib", "libLimeSuite.dylib", "LimeSuite.dll"] {
                let p = dir.join(rel);
                if p.exists() {
                    out.push(p.into_os_string());
                }
            }
        }
    }

    for n in ["libLimeSuite.so", "libLimeSuite.dylib", "LimeSuite.dll"] {
        out.push(n.into());
    }

    // The unversioned symlink above comes with the development package alone,
    // so a machine with only the runtime is found by scanning for the soname
    // it happens to have. Newest first: 23.11 sorts above 20.10.
    let mut versioned: Vec<OsString> = Vec::new();
    for dir in [
        "/usr/lib/x86_64-linux-gnu",
        "/usr/lib/aarch64-linux-gnu",
        "/usr/lib",
        "/usr/local/lib",
        "/opt/homebrew/lib",
    ] {
        let Ok(rd) = std::fs::read_dir(dir) else { continue };
        for e in rd.flatten() {
            let name = e.file_name();
            let s = name.to_string_lossy();
            if s.starts_with("libLimeSuite.so.")
                || (s.starts_with("libLimeSuite.") && s.ends_with(".dylib"))
            {
                versioned.push(e.path().into_os_string());
            }
        }
    }
    versioned.sort();
    versioned.reverse();
    out.extend(versioned);
    out
}

/// One `pub unsafe fn` per LMS call, forwarding to the opened library and
/// giving a failure back when there is none.
macro_rules! shims {
    ($(fn $name:ident($($arg:ident: $ty:ty),* $(,)?) -> $ret:ty = $absent:expr;)*) => {$(
        pub unsafe fn $name($($arg: $ty),*) -> $ret {
            match lib() {
                Some(l) => unsafe { l.$name($($arg),*) },
                None => $absent,
            }
        }
    )*};
}

type c_int = ::std::os::raw::c_int;
type c_uint = ::std::os::raw::c_uint;
type c_char = ::std::os::raw::c_char;
type c_void = ::std::os::raw::c_void;

shims! {
    fn LMS_GetDeviceList(dev_list: *mut lms_info_str_t) -> c_int = LMS_ERROR;
    fn LMS_Open(device: *mut *mut lms_device_t, info: *const c_char, args: *mut c_void) -> c_int = LMS_ERROR;
    fn LMS_Close(device: *mut lms_device_t) -> c_int = LMS_ERROR;
    fn LMS_Init(device: *mut lms_device_t) -> c_int = LMS_ERROR;
    fn LMS_GetDeviceInfo(device: *mut lms_device_t) -> *const lms_dev_info_t = std::ptr::null();
    fn LMS_GetLastErrorMessage() -> *const c_char = c"LimeSuite is not installed".as_ptr();
    fn LMS_GetNumChannels(device: *mut lms_device_t, dir_tx: bool) -> c_int = LMS_ERROR;
    fn LMS_EnableChannel(device: *mut lms_device_t, dir_tx: bool, chan: usize, enabled: bool) -> c_int = LMS_ERROR;
    fn LMS_SetSampleRate(device: *mut lms_device_t, rate: float_type, oversample: usize) -> c_int = LMS_ERROR;
    fn LMS_GetSampleRate(device: *mut lms_device_t, dir_tx: bool, chan: usize, host_Hz: *mut float_type, rf_Hz: *mut float_type) -> c_int = LMS_ERROR;
    fn LMS_GetSampleRateRange(device: *mut lms_device_t, dir_tx: bool, range: *mut lms_range_t) -> c_int = LMS_ERROR;
    fn LMS_SetLOFrequency(device: *mut lms_device_t, dir_tx: bool, chan: usize, frequency: float_type) -> c_int = LMS_ERROR;
    fn LMS_GetLOFrequency(device: *mut lms_device_t, dir_tx: bool, chan: usize, frequency: *mut float_type) -> c_int = LMS_ERROR;
    fn LMS_GetAntennaList(dev: *mut lms_device_t, dir_tx: bool, chan: usize, list: *mut lms_name_t) -> c_int = LMS_ERROR;
    fn LMS_SetAntenna(dev: *mut lms_device_t, dir_tx: bool, chan: usize, index: usize) -> c_int = LMS_ERROR;
    fn LMS_GetAntennaBW(dev: *mut lms_device_t, dir_tx: bool, chan: usize, index: usize, range: *mut lms_range_t) -> c_int = LMS_ERROR;
    fn LMS_SetGaindB(device: *mut lms_device_t, dir_tx: bool, chan: usize, gain: c_uint) -> c_int = LMS_ERROR;
    fn LMS_GetGaindB(device: *mut lms_device_t, dir_tx: bool, chan: usize, gain: *mut c_uint) -> c_int = LMS_ERROR;
    fn LMS_SetLPFBW(device: *mut lms_device_t, dir_tx: bool, chan: usize, bandwidth: float_type) -> c_int = LMS_ERROR;
    fn LMS_GetLPFBWRange(device: *mut lms_device_t, dir_tx: bool, range: *mut lms_range_t) -> c_int = LMS_ERROR;
    fn LMS_Calibrate(device: *mut lms_device_t, dir_tx: bool, chan: usize, bw: f64, flags: c_uint) -> c_int = LMS_ERROR;
    fn LMS_SetTestSignal(device: *mut lms_device_t, dir_tx: bool, chan: usize, sig: lms_testsig_t, dc_i: i16, dc_q: i16) -> c_int = LMS_ERROR;
    fn LMS_GetChipTemperature(dev: *mut lms_device_t, ind: usize, temp: *mut float_type) -> c_int = LMS_ERROR;
    fn LMS_SetupStream(device: *mut lms_device_t, stream: *mut lms_stream_t) -> c_int = LMS_ERROR;
    fn LMS_DestroyStream(dev: *mut lms_device_t, stream: *mut lms_stream_t) -> c_int = LMS_ERROR;
    fn LMS_StartStream(stream: *mut lms_stream_t) -> c_int = LMS_ERROR;
    fn LMS_StopStream(stream: *mut lms_stream_t) -> c_int = LMS_ERROR;
    fn LMS_RecvStream(stream: *mut lms_stream_t, samples: *mut c_void, sample_count: usize, meta: *mut lms_stream_meta_t, timeout_ms: c_uint) -> c_int = LMS_ERROR;
    fn LMS_SendStream(stream: *mut lms_stream_t, samples: *const c_void, sample_count: usize, meta: *const lms_stream_meta_t, timeout_ms: c_uint) -> c_int = LMS_ERROR;
    fn LMS_GetStreamStatus(stream: *mut lms_stream_t, status: *mut lms_stream_status_t) -> c_int = LMS_ERROR;
}

#[cfg(test)]
mod tests {
    /// The library this was built against is on the build machine, so it has
    /// to be found by name too: a build that links nothing and then finds
    /// nothing reads no LimeSDR anywhere.
    #[test]
    fn opens_the_library() {
        assert!(super::available());
        let n = unsafe { super::LMS_GetDeviceList(std::ptr::null_mut()) };
        assert!(n >= 0, "device list returned {n}");
    }
}
