//! Robot 36, against a transmission whose source picture is known.
//!
//! `testdata/sstv_robot36_bars_44100.wav` was generated by pySSTV from colour
//! bars, so what should come out is not a judgement: white, yellow, cyan,
//! green, magenta, red and blue across the top half, and a red-to-green ramp
//! at constant blue across the bottom.
//!
//! Robot 36 sends one colour difference a line, R-Y on the even lines and
//! B-Y on the odd, so a line borrows the other half from its neighbour. Two
//! ways of getting that wrong give a picture that still looks like a picture
//! on a photograph, and both were here: the differences swapped, and an even
//! line borrowing from the line before it instead of the one after. On bars
//! they are obvious, which is the reason this fixture is bars.

use decode::sstv;

const FIXTURE: &str = "../../testdata/sstv_robot36_bars_44100.wav";

fn picture() -> Option<sstv::Picture> {
    let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE);
    if !p.exists() {
        eprintln!("skipping: {FIXTURE} absent, run testdata/fetch.sh to enable");
        return None;
    }
    let raw = std::fs::read(&p).ok()?;
    let rate = u32::from_le_bytes([raw[24], raw[25], raw[26], raw[27]]) as f64;
    let audio: Vec<f32> = raw[44..]
        .chunks_exact(2)
        .map(|c| i16::from_le_bytes([c[0], c[1]]) as f32 / 32768.0)
        .collect();
    sstv::decode(&audio, rate)
}

fn pixel(p: &sstv::Picture, x: usize, y: usize) -> (u8, u8, u8) {
    let at = (y * p.width + x) * 3;
    (p.rgb[at], p.rgb[at + 1], p.rgb[at + 2])
}

#[test]
fn the_bars_come_out_in_the_order_they_were_sent() {
    let Some(p) = picture() else { return };
    assert_eq!(p.mode.name, "Robot 36");
    assert_eq!((p.width, p.height), (320, 240));
    // One line short of the frame: the last line's colour difference has no
    // neighbour to pair with, and the transmission ends before it.
    assert_eq!(p.lines, 239, "lines decoded");

    let bars: [(&str, (u8, u8, u8)); 7] = [
        ("white", (255, 255, 255)),
        ("yellow", (255, 255, 0)),
        ("cyan", (0, 255, 255)),
        ("green", (0, 255, 0)),
        ("magenta", (255, 0, 255)),
        ("red", (255, 0, 0)),
        ("blue", (0, 0, 255)),
    ];
    // Two lines, one even and one odd, because the two carry different
    // halves of the colour and a bug in one is invisible in the other.
    for y in [30usize, 31] {
        for (i, (name, want)) in bars.iter().enumerate() {
            let x = i * 320 / 7 + 320 / 14;
            let got = pixel(&p, x, y);
            // Which bar it is, rather than how many counts off it is. The
            // colour differences are sent at half the picture's resolution
            // and read through a window several pixels wide, so a saturated
            // bar lands tens of counts from where it started; what must not
            // happen is cyan reading as green.
            let nearest = bars
                .iter()
                .enumerate()
                .min_by_key(|(_, (_, c))| {
                    let d = |a: u8, b: u8| (a as i64 - b as i64).pow(2);
                    d(got.0, c.0) + d(got.1, c.1) + d(got.2, c.2)
                })
                .map(|(k, _)| k)
                .unwrap_or(usize::MAX);
            assert_eq!(nearest, i, "line {y}: the {name} bar read as {got:?}");
            let _ = want;
        }
    }
}

/// The ramp says the luminance scale is right and the colour is not being
/// borrowed from the wrong line: a picture built from the neighbour above
/// instead of below shows it as a stair rather than a slope.
#[test]
fn the_ramp_rises_across_the_picture() {
    let Some(p) = picture() else { return };
    let y = 180;
    let left = pixel(&p, 20, y);
    let mid = pixel(&p, 160, y);
    let right = pixel(&p, 300, y);
    assert!(left.0 < mid.0 && mid.0 < right.0, "red rises: {left:?} {mid:?} {right:?}");
    assert!(left.1 > mid.1 && mid.1 > right.1, "green falls: {left:?} {mid:?} {right:?}");
    for (at, px) in [("left", left), ("middle", mid), ("right", right)] {
        assert!((px.2 as i32 - 128).abs() < 60, "blue is constant, {at} read {}", px.2);
    }
}
